config/routes.rb
Rails.application.routes.draw do
  get 'recipe_ingredients/new'
  get 'ingredients/new'
  root 'static_pages#home'

  resources :users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'recipes/index'
  get 'ratings/new'
  get 'categories/index'

  resources :users

  resources :categories do
    resources :recipes, only: [:index, :show]
  end

  resources :recipes do
    resources :categories, only: [:new, :create, :index]
    resources :recipe_ingredients, only: [:new, :create, :index]
  end
  
  resources :recipe_ingredients do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :ratings, only: [:new, :create]

  get 'newest_recipe', to: 'recipes#newest_recipe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :ratings

  validates :name, presence: true
  validates :cooking_time, numericality: { only_integer: true }
  validates :servings, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 20, message: "can't be blank and has to be a number between 1 and 20" }
  validates :directions, presence: true

  accepts_nested_attributes_for :categories

  scope :newest, -> { order('created_at DESC').limit(1) }

  def self.by_name(name)
    where(['name LIKE ?', "%#{name}%"])
  end

  def self.by_user(user_id)
    where(user: user_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login, except: [:index, :show, :newest_recipe]
  before_action :admin_only, except: [:index, :show, :newest_recipe]
  before_action :set_recipe, except: [:index, :new, :create, :newest_recipe]

  def index
    @users = User.all
    @categories = Category.all
    @recipes = Recipe.all

    if !params[:name].blank?
      @recipes = Recipe.by_name(params[:name])
    elsif !params[:user].blank?
      @recipes = Recipe.by_user(params[:user])
    else
      @recipes = Recipe.all
    end
  end

  def new
    @recipe = Recipe.new
    5.times { @recipe.recipe_ingredients.build }
    2.times { @recipe.recipe_categories.build }
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
  end

  def edit 
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  def newest_recipe
    @recipe = Recipe.newest.first
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :servings, :directions)
  end

  def set_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for@recipe do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %><br>
  </div>
  <div class="form-group">
    <%= f.label :cooking_time %><%= " in minutes" %>
    <%= f.number_field :cooking_time, min:1, :class => "form-control" %><br>
  </div>
  <div class="form-group">
    <%= f.label :servings %>
    <%= f.number_field :servings, min:1, max:20, :class => "form-control" %><br>
  </div>
  <div class="form-group">
    <%= f.label :directions %>
    <%= f.text_area :directions, size: "24x6", :class => "form-control" %><br>
  </div>
  <div class="form-group">
    <p>Select a category:</p>
    <%= f.collection_select(:category_ids, Category.all, :id, :name, {include_blank: 'Select a category'}, { multiple: true, :style => "width:150px", :class => "form-control" }) %>
  </div>
  <button type=f.submit class="btn btn-primary">Submit</button>
<% end %>

app/views/recipes/_recipe_info.html.erb
<% if @recipe %>
  <div class="container text-center">
    <h1><%= @recipe.name %></h1>
    <br />
  </div>
  <div class="container">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Cooking time in minutes: <%= @recipe.cooking_time %></li>
      <li class="list-group-item">Servings: <%= @recipe.servings %></li>
      <li class="list-group-item">Directions: <%= @recipe.directions %></li>
      <% if not_empty @recipe.ingredients %>
        <li class="list-group-item">Ingredients: <% @recipe.recipe_ingredients.each do |ri| %>
          <%= ri.ingredient.name %> 
          (<%= ri.quantity %>)
        <% end %></li>
      <% end %>
      <% if not_empty @recipe.categories %>
        <li class="list-group-item">Categories: <% @recipe.categories.each do |category| %>
          <%= category.name %>
        <% end %></li>
      <% end %>
    </ul>
    <strong><li class="list-group-item">Recipe created by <%= @recipe.user.user_name %></li></strong>
  </div>
  <br />
  <div class="container">
    <% if not_empty @recipe.ratings %>
      <h6><strong>Ratings:</strong></h6>
      <% @recipe.ratings.each do |rating| %>
        <p><%= rating.score %> star -
        <strong><%= rating.user.first_name %></strong><br /></p>
      <% end %>
    <% end %>
  </div>
  <div class="container">
    <% if current_user.admin %>
      <div class="btn btn-primary">
        <%= link_to "Add an ingredient", new_recipe_recipe_ingredient_path(@recipe), :class => "btn text-white" %>
      </div>

      <% if not_empty @recipe.ingredients %>
        <div class="btn btn-primary">
          <%= link_to "Delete ingredient", recipe_recipe_ingredients_path(@recipe), :class => "btn text-white" %>
        </div>
      <% end %>

      <div class="btn btn-primary">
        <%= link_to "Edit recipe", edit_recipe_path(@recipe), :class => "btn text-white" %>
      </div>

      <div class="btn btn-primary">
        <%= link_to "Delete recipe", @recipe, method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, :class => "btn text-white" %>
      </div>

      <div class="btn btn-primary">
        <%= link_to "Back", root_path, :class => "btn text-white" %>
      </div>
      
    <% end %>
    <div class="btn btn-primary">
        <%= link_to "Back", root_path, :class => "btn text-white" %>
      </div>
   </div>
<% end %>

app/views/recipes/edit.html.erb
<% if @recipe %>
  <%= render partial: 'layouts/navbar' %>
  <div class="container text-center">
    <h1>Edit <%= @recipe.name %></h1>
    <br /><br />
  </div>
  <div class="container">
    <%= render partial: 'layouts/errors', locals: {object: @recipe}  %>
    <%= render 'form' %>
  </div>
<% end %> 

app/views/recipes/index.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <h1>Our recipes</h1>
</div> 

<div class="container">
  <%= form_tag("/recipes", method: "get", :class => "form") do %>
    <p>Search by recipe name:</p>
    <%= text_field_tag :name, params[:name], :class => "form-control mr-sm-2", :placeholder => "Recipe name" %><br /><br />
    <p>Or by recipe author:  
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "user_name"), {include_blank: true} %></p><br />
    <button type=submit_tag class="btn btn-outline-success my-2 my-sm-0">Search</button>
    <br /><br /><br />
  <% end%>

  <ul class="list-group list-group-flush">
    <% @recipes.each do |recipe| %>
      <%= link_to recipe.name, recipe_path(recipe), :class => "list-group-item" %>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <h1>Create a new recipe</h1>
  <br /><br />
</div>
<div class="container">
  <%= render partial: 'layouts/errors', locals: {object: @recipe} %>
  <%= render 'form' %>
</div> 

app/views/recipes/newest_recipe.html.erb
<%= render partial: 'layouts/navbar' %>

<%= render 'recipe_info' %> 

app/views/recipes/show.html.erb
<% if @recipe %>
  <h1><%= @recipe.name %></h1>
  <p>Cooking time in minutes: <%= @recipe.cooking_time %></p>
  <p>Servings: <%= @recipe.servings %></p>
  <p>Directions: <%= @recipe.directions %></p>

  <% if @recipe.ingredients.size >= 1 %>
    <p>Ingredients: <% @recipe.recipe_ingredients.each do |ri| %></p>
      <p><%= ri.ingredient.name %></p>
      <p><%= ri.quantity %></p>
    <% end %>
  <% end %>

  <% if @recipe.categories.size >= 1 %>
    <p>Categories: <% @recipe.categories.each do |category| %></p>
      <p><%= category.name %></p>
    <% end %>
  <% end %>

  <strong><p>Created by <%= @recipe.user.name %></p></strong>

  <% if @recipe.user.admin %>
    <p><%= link_to "Add a ingredient to this recipe", new_recipe_recipe_ingredient_path(@recipe) %></p>
    <p><%= link_to "Add a category to this recipe", new_recipe_category_path(@recipe) %></p>
    <p><%= link_to "Edit this recipe", edit_recipe_path(@recipe) %></p>
  <% end %>

  <p><%= link_to "Delete this recipe", @recipe, method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" } %></p>

  <% if @recipe.ratings.size >= 1 %>
    <p>Ratings:</p>
    <% @recipe.ratings.each do |rating| %>
      <%= rating.score %>
      <strong><%= rating.user.name %></strong><br />
    <% end %>
  <% end %>
<% end %>