config/routes.rb
Rails.application.routes.draw do
  get 'recipe_ingredients/new'
  get 'ingredients/new'
  root 'static_pages#home'

  resources :users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'recipes/index'
  get 'ratings/new'
  get 'categories/index'

  resources :users

  resources :categories do
    resources :recipes, only: [:index, :show]
  end

  resources :recipes do
    resources :categories, only: [:new, :create, :index]
    resources :recipe_ingredients, only: [:new, :create, :index]
  end
  
  resources :recipe_ingredients do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :ratings, only: [:new, :create]

  get 'newest_recipe', to: 'recipes#newest_recipe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :ratings

  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :user_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
                    uniqueness: true

  validates :email, confirmation: true

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  before_save :email_to_downcase


  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if current_user.id == params[:id].to_i
      @user
    else
      flash[:error] = 'Sorry, you are authorized to access only your profile page'
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/most_popular_user.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <h1><%= @user.user_name%> is our most popular user</h1>
</div>

app/views/users/new.html.erb
<div class="container text-center">
  <%= render partial: 'layouts/errors', locals: {object: @user}  %>
  <h1>Sign up</h1><br />
  <%= form_for@user do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <p>Admin? <%= f.check_box :admin %></p><br>
    <br>

    <button type=f.submit class="btn btn-primary">Sign Up</button>
  <% end %>
</div> 

app/views/users/show.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <% if flash[:error] %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <%= flash[:error] %>
      </div>
    </div>
  <% end %>

  <h1>Welcome <%= @user.user_name%></h1>
  <br />
  <div class="list-group">
    <%= link_to "Rate a recipe", new_rating_path, :class => "list-group-item list-group-item-action"%>
    <% if @user.admin %>
      <%= link_to "New recipe", new_recipe_path, :class => "list-group-item list-group-item-action"%>
      <%= link_to "New category", new_category_path, :class => "list-group-item list-group-item-action"%>
    <% end %>
  </div>
</div> 