config/routes.rb
Rails.application.routes.draw do
  get 'recipe_ingredients/new'
  get 'ingredients/new'
  root 'static_pages#home'

  resources :users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'recipes/index'
  get 'ratings/new'
  get 'categories/index'

  resources :users

  resources :categories do
    resources :recipes, only: [:index, :show]
  end

  resources :recipes do
    resources :categories, only: [:new, :create, :index]
    resources :recipe_ingredients, only: [:new, :create, :index]
  end
  
  resources :recipe_ingredients do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :ratings, only: [:new, :create]

  get 'newest_recipe', to: 'recipes#newest_recipe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

  validates :name, uniqueness: true, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login
  before_action :admin_only, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])
    @recipes = @category.recipes
  end

  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% if @categories %>
  <%= render partial: 'layouts/navbar' %>
    <div class="container text-center">
      <h1>Categories</h1>
    </div>
    <div class="container">
      <ul class="list-group list-group-flush">
        <% @categories.each do |category| %>
          <%= link_to category.name, category_path(category), :class => "list-group-item" %>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/categories/new.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <h1>New category</h1>
  <br /><br />
</div>

<div class="container">
  <%= render partial: 'layouts/errors', locals: {object: @category}  %>
  <%= form_with model: @category do |f|%>
    <div>
      <%= f.label :name, "Category name:  " %>
      <%= f.text_field :name %>
    </div>
    <br>
    <button type=f.submit class="btn btn-primary">Create categoty</button>
  <% end %>
</div> 

app/views/categories/show.html.erb
<%= render partial: 'layouts/navbar' %>
<div class="container text-center">
  <h1>Recipes for <%= @category.name %> category</h1>
</div>
<div class="container">
  <% @recipes.each do |recipe| %>
    <ul class="list-group list-group-flush">
      <%= link_to recipe.name, category_recipe_path(@category, recipe), :class => "list-group-item" %>
    </ul>
  <% end %>
</div> 