config/routes.rb
Rails.application.routes.draw do
  get 'recipe_ingredients/new'
  get 'ingredients/new'
  root 'static_pages#home'

  resources :users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'recipes/index'
  get 'ratings/new'
  get 'categories/index'

  resources :users

  resources :categories do
    resources :recipes, only: [:index, :show]
  end

  resources :recipes do
    resources :categories, only: [:new, :create, :index]
    resources :recipe_ingredients, only: [:new, :create, :index]
  end
  
  resources :recipe_ingredients do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :ratings, only: [:new, :create]

  get 'newest_recipe', to: 'recipes#newest_recipe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipe_categories
  has_many :recipes, through: :recipe_categories

  validates :name, uniqueness: true, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true, uniqueness: {message: "should be unique"}
  validates :name, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :score, :numericality => { greater_than_or_equal_to: 1, less_than_or_equal_to: 5, message: "shouldn't be blank and should be a number between 1 and 5" }
  validates :user_id, uniqueness: { scope: :recipe_id, message: 'you can make one rating per recipe'}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipe_categories
  has_many :categories, through: :recipe_categories

  has_many :ratings

  validates :name, presence: true
  validates :cooking_time, numericality: { only_integer: true }
  validates :servings, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 20, message: "can't be blank and has to be a number between 1 and 20" }
  validates :directions, presence: true

  accepts_nested_attributes_for :categories

  scope :newest, -> { order('created_at DESC').limit(1) }

  def self.by_name(name)
    where(['name LIKE ?', "%#{name}%"])
  end

  def self.by_user(user_id)
    where(user: user_id)
  end
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :category_id, uniqueness: { scope: :recipe_id, message: 'should have one type of category per recipe' }
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient

  accepts_nested_attributes_for :ingredient

  validates :quantity, numericality: { only_integer: true, message: 'should be added and should be a number' }
  validates :ingredient_id, uniqueness: { scope: :recipe_id, message: 'should have one type of ingredient per recipe'}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :ratings

  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :user_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
                    uniqueness: true

  validates :email, confirmation: true

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  before_save :email_to_downcase


  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :require_login

  def new
    @rating = Rating.new
  end

  def create
    @rating = current_user.ratings.build(rating_params)
    if @rating.save
      redirect_to recipe_path(@rating.recipe)
    else
      render :new
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:recipe_id, :score)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :require_login, except: [:index, :show, :newest_recipe]
  before_action :admin_only, except: [:index, :show, :newest_recipe]
  before_action :set_recipe, except: [:index, :new, :create, :newest_recipe]

  def index
    @users = User.all
    @categories = Category.all
    @recipes = Recipe.all

    if !params[:name].blank?
      @recipes = Recipe.by_name(params[:name])
    elsif !params[:user].blank?
      @recipes = Recipe.by_user(params[:user])
    else
      @recipes = Recipe.all
    end
  end

  def new
    @recipe = Recipe.new
    5.times { @recipe.recipe_ingredients.build }
    2.times { @recipe.recipe_categories.build }
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
  end

  def edit 
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  def newest_recipe
    @recipe = Recipe.newest.first
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :servings, :directions)
  end

  def set_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.find_by(:email => params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id

      redirect_to user_path(@user)
    else
      flash[:error] = 'Login info was incorrect. Please try again.'
      render :new
    end
  end

  def destroy
    if current_user
      session.delete :user_id
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id

      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if current_user.id == params[:id].to_i
      @user
    else
      flash[:error] = 'Sorry, you are authorized to access only your profile page'
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def not_empty(collection)
    collection.size >= 1
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div class="alert alert-danger" role="alert">
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
      <% object.errors.full_messages.each do |msg| %>
        <%= msg %><br />
      <% end %>
    </div>
  </div>
<% end %> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <%= link_to 'Home', user_path(current_user), :class => "navbar-brand" %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to "Recipes", recipes_path, :class => "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Newest Recipe", newest_recipe_path, :class => "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Categories", categories_path, :class => "nav-link" %>
      </li>
    </ul>
    <%= link_to "Log out", logout_path, method: :delete, :class => "navbar-brand" %>
  </div>
</nav>
<br /><br /> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <!-- Footer -->
      <footer class="page-footer font-small blue bottom">

      <!-- Copyright -->
        <div class="container">
          <div class="footer-copyright text-center py-3 fixedbottom">© 2020 Copyright by: Gzim Iseni
            <a href="https://github.com/gzim921">Recipe</a>
          </div>
        </div>
      <!-- Copyright -->

      </footer>
    <!-- Footer -->

  </body>
</html>